In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score, recall_score

In [2]:
df=pd.read_csv("Social_Network_Ads.csv")

In [3]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
df.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [5]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [6]:
# Split the dataset into features (X) and target variable (y)
x = df[['Age','EstimatedSalary']]
y = df[['Purchased']]

In [36]:
# x = df[['Age','EstimatedSalary']].to_numpy()

In [7]:
x


Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [38]:
# y = df[['Purchased']].to_numpy()

In [8]:
y

Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [9]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [10]:
X_train

Age  EstimatedSalary
3     27            57000
18    46            28000
202   39           134000
250   44            39000
274   57            26000
..   ...              ...
71    24            27000
106   26            35000
270   43           133000
348   39            77000
102   32            86000

[320 rows x 2 columns]

In [11]:
X_test

Age  EstimatedSalary
209   46            22000
280   59            88000
33    28            44000
210   48            96000
93    29            28000
..   ...              ...
246   35            50000
227   56           133000
369   54            26000
176   35            47000
289   37            78000

[80 rows x 2 columns]

In [51]:
X_test

array([[    46,  22000],
       [    59,  88000],
       [    28,  44000],
       [    48,  96000],
       [    29,  28000],
       [    30,  62000],
       [    47, 107000],
       [    29,  83000],
       [    40,  75000],
       [    42,  65000],
       [    35,  65000],
       [    53,  34000],
       [    23,  48000],
       [    20,  23000],
       [    30,  87000],
       [    35, 108000],
       [    52,  38000],
       [    46,  74000],
       [    39,  42000],
       [    56,  60000],
       [    22,  27000],
       [    29,  80000],
       [    47,  23000],
       [    59,  76000],
       [    19,  19000],
       [    51,  23000],
       [    42,  80000],
       [    37,  53000],
       [    55, 125000],
       [    19,  21000],
       [    46,  41000],
       [    19,  70000],
       [    36, 144000],
       [    28,  79000],
       [    40, 107000],
       [    35,  75000],
       [    37,  55000],
       [    38,  65000],
       [    26,  30000],
       [    18,  68000],


In [12]:
y_train

Purchased
3            0
18           1
202          1
250          0
274          1
..         ...
71           0
106          0
270          0
348          0
102          0

[320 rows x 1 columns]

In [44]:
y_test

array([[0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1]], dtype=int64)

In [13]:
y_test

Purchased
209          0
280          1
33           0
210          1
93           0
..         ...
246          0
227          1
369          1
176          0
289          1

[80 rows x 1 columns]

In [14]:
reg=LogisticRegression()

In [15]:
reg

LogisticRegression()

In [16]:
reg.fit(X_train,y_train)

C:\Users\91620\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [17]:

# Make predictions on the test set
y_pred = reg.predict(X_test)


In [18]:
# Compute the confusion matrix

cm=confusion_matrix(y_test,y_pred)


In [20]:
TN = cm[0,0]
FP = cm[0,1]
FN = cm[1,0]
TP = cm[1,1]

In [22]:
Accuracy=(TP+TN)/(TP+FP+FN+TP)
Error_rate=(FN+FP)/(TP+FP+FN+TP)
Precision = TP / (TP + TN + FP + FN)
Recall = TP / (TP + TN + FP + FN)

In [24]:
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[52  0]
 [28  0]]


In [25]:
print("True Positives:", TP)
print("False Positives:", FP)
print("True Negatives:", TN)
print("False Negatives:", FN)

True Positives: 0
False Positives: 0
True Negatives: 52
False Negatives: 28


In [27]:
print("Accuracy:", Accuracy)
print("Error Rate:", Error_rate)
print("Precision:", Precision)
print("Recall:", Recall)

Accuracy: 1.8571428571428572
Error Rate: 1.0
Precision: 0.0
Recall: 0.0
